### ISSUE TITLE
Fails with django 3.0 and python3.8

### ISSUE THREAD

**Issue by JustDevZero** [scoursen/django-softdelete#63]
Hi there,

This is failing on django 3.0 and python 3.8, with the following error:
```

Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/dev/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/dev/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/dev/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dev/venv/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/dev/venv/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dev/venv/lib/python3.8/site-packages/softdelete/models.py", line 10, in <module>
    from django.utils.encoding import python_2_unicode_compatible

```

I guess that's because in django 3 they dropped out all the python2 compatibility. Maybe launching a new version to all that stuff removed could be nice. It's time for python3 already :D

**Comment by TAnas0** [comment]
This issue has been resolved it seems
@scoursen Should this be close
